# Generated by Django 5.1.3 on 2024-12-18 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheNextGame', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
