# Generated by Django 5.1.3 on 2024-12-21 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_remove_game_category_game_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='game',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='game',
            name='release_date',
        ),
    ]
