# Generated by Django 5.1.4 on 2025-01-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_game_awards_remove_game_manufacturer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='number_of_players',
        ),
        migrations.RemoveField(
            model_name='game',
            name='price_range',
        ),
        migrations.RemoveField(
            model_name='game',
            name='recommended_age',
        ),
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='max_play_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='max_players',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='mechanics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='min_play_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='min_players',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='publisher',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='year_published',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
